version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: "mysql:8.0.36"
    container_name: airbnb-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: airbnb!@#
      MYSQL_DATABASE: airbnb
      MYSQL_USER: airbnb
      MYSQL_PASSWORD: airbnb!@#
      MYSQL_ROOT_HOST: '%'
      # 문자 인코딩 설정
      MYSQL_CHARSET: 'utf8mb4'
      MYSQL_COLLATION: 'utf8mb4_unicode_ci'
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --bind-address=0.0.0.0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-tier

  mongo:
    image: "mongo:8.0-rc"
    container_name: airbnb-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--noauth"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo-data:/data/db
      - ./setup/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-tier
  #
  localstack:
    container_name: airbnb-localstack
    image: localstack/localstack:3.6
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-2
      - DEBUG=1
    volumes:
      - './localstack:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./setup/s3/init.sh:/etc/localstack/init/ready.d/init-localstack.sh"
    networks:
      - app-tier
    depends_on:
      - mongo
  #
  redis:
      container_name: airbnb-redis
      image: redis:7.4.0
      restart: unless-stopped
      ports:
      - "6379:6379"
      networks:
      - app-tier
      volumes:
      - redis-data:/data

volumes:
  mysql-data:
  mongo-data:
  redis-data:
