spring:
  sql:
    init:
      mode: always
  config:
    import:
      - optional:file:backend-config-secret/s3-secret-file.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/airbnb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: airbnb
    password: airbnb!@#
  data:
    mongodb:
      uri: mongodb://mongo:27017/airbnb
      database: airbnb
    redis:
      host: redis
      port: 6379

  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        accelerate-mode-enabled: true
        bucket-name: airbnb-clone-be-bucket
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
