spring:
  application:
    name: airbnb
  profiles:
    active: local
  jwt:
    secret: awergfownmefoiwneiofnjasdfiuhlasiefhiluasefsefsefliuahsergiadrgasd
  config:
    import: optional:file:backend-oauth-secret/oauth2-secret-file.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile,email
server:
  port: 8008
