spring:
  application:
    name: airbnb
  profiles:
    active: local
  jwt:
    secret: awergfownmefoiwneiofnjasdfiuhlasiefhiluasefsefsefliuahsergiadrgasd
  config:
    import: optional:file:backend-oauth-secret/oauth2-secret-file.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile,email
server:
  port: 8008

management:
  server:
    port: 8008
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
logging:
  file:
    name: log/airbnb.log
  logback:
    rollingpolicy:
      file-name-pattern: log/airbnb.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10KB
  pattern:
    dateformat: Asia/Seoul

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html


