spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/airbnb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: airbnb
    password: airbnb!@#
  data:
    mongodb:
      uri: mongodb://mongo:27017/airbnb
      database: airbnb

  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        accelerate-mode-enabled: true
        bucket-name: airbnb-clone-be-bucket
      region:
        static: ap-northeast-2
