-- 주제 (Topics)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (1, '요리', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (2, '베이킹', 1);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (3, '그릴', 1);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (4, '비건', 1);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (5, '디저트', 1);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (6, '여행', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (7, '백패킹', 6);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (8, '럭셔리 여행', 6);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (9, '로드트립', 6);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (10, '도시 탐방', 6);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (11, '패션', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (12, '캐주얼웨어', 11);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (13, '포멀웨어', 11);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (14, '스트릿패션', 11);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (15, '빈티지', 11);

-- 스타일 (Styles)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (16, '인테리어', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (17, '미니멀리즘', 16);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (18, '북유럽', 16);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (19, '보헤미안', 16);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (20, '산업적', 16);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (21, '그래픽 디자인', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (22, '플랫 디자인', 21);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (23, '타이포그래피', 21);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (24, '일러스트레이션', 21);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (25, '레트로', 21);

-- 기술 (Techniques)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (26, '사진', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (27, '매크로', 26);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (28, '장노출', 26);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (29, 'HDR', 26);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (30, '포트레이트', 26);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (31, '미술', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (32, '수채화', 31);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (33, '유화', 31);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (34, '디지털 아트', 31);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (35, '스케치', 31);

-- 이벤트 (Events)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (36, '계절', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (37, '봄', 36);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (38, '여름', 36);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (39, '가을', 36);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (40, '겨울', 36);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (41, '휴일', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (42, '크리스마스', 41);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (43, '할로윈', 41);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (44, '추수감사절', 41);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (45, '설날', 41);

-- 감정 (Emotions)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (46, '긍정적', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (47, '행복', 46);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (48, '평화', 46);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (49, '열정', 46);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (50, '영감', 46);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (51, '부정적', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (52, '슬픔', 51);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (53, '불안', 51);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (54, '분노', 51);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (55, '외로움', 51);

-- 대상 그룹 (Target Groups)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (56, '연령대', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (57, '어린이', 56);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (58, '십대', 56);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (59, '성인', 56);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (60, '노인', 56);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (61, '직업', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (62, '학생', 61);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (63, '직장인', 61);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (64, '프리랜서', 61);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (65, '은퇴자', 61);

-- 색상 (Colors)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (66, '톤', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (67, '파스텔', 66);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (68, '비비드', 66);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (69, '어스톤', 66);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (70, '모노크롬', 66);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (71, '구체적 색상', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (72, '레드', 71);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (73, '블루', 71);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (74, '그린', 71);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (75, '퍼플', 71);

-- 장소 (Places)
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (76, '자연', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (77, '해변', 76);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (78, '산', 76);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (79, '숲', 76);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (80, '사막', 76);

INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (81, '도시', NULL);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (82, '뉴욕', 81);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (83, '파리', 81);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (84, '도쿄', 81);
INSERT INTO CATEGORY (NO, NAME, PARENT_NO) VALUES (85, '런던', 81);
