CREATE TABLE IF NOT EXISTS USERS
(
    NO              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '사용자 고유번호',
    USERNAME        VARCHAR(255) UNIQUE NOT NULL COMMENT '이메일',
    IS_SOCIAL       BOOLEAN             NOT NULL COMMENT '소셜 아이디 여부',
    PASSWORD        VARCHAR(1024) COMMENT '비밀번호',
    BIRTHDAY        DATE COMMENT '생년월일',
    GENDER          VARCHAR(255) COMMENT '성별',
    DESCRIPTION     VARCHAR(255) COMMENT '설명',

    FIRST_NAME      VARCHAR(255) COMMENT '이름, 유저 닉네임',
    LAST_NAME       VARCHAR(255) COMMENT '성, 유저 닉네임',
    PROFILE_IMG_URL VARCHAR(2048) COMMENT '프로필 이미지 URL',
    SPOKEN_LANGUAGE VARCHAR(255) COMMENT '사용자 언어',
    COUNTRY         VARCHAR(255) COMMENT '사용자 국가',

    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BOARD
(
    NO         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '보드 고유번호',
    NAME       VARCHAR(255) UNIQUE NOT NULL COMMENT '보드 이름',
    USER_NO    BIGINT COMMENT '유저고유번호 (FK)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PIN
(
    NO                 BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '핀 고유번호',
    USER_NO            BIGINT        NOT NULL COMMENT '핀 작성자 고유번호(FK)',
    IMG_URL            VARCHAR(1024) NOT NULL COMMENT '핀 이미지 URL',
    TITLE              VARCHAR(255) COMMENT '핀 제목',
    DESCRIPTION        TEXT COMMENT '핀 설명',
    LINK               VARCHAR(2000) COMMENT '링크 URL',
    BOARD_NO           BIGINT        NOT NULL COMMENT '보드 종류(FK)',
    IS_COMMENT_ALLOWED BOOLEAN       NOT NULL DEFAULT TRUE COMMENT '댓글 달기 허용여부',
    LIKE_COUNT         INT                    DEFAULT 0 COMMENT '좋아요 수',
    IS_PIN_DELETED     BOOLEAN                DEFAULT FALSE COMMENT '핀 삭제 여부',
    IMAGE_CLASSIFICATION VARCHAR(255) COMMENT '이미지 분류',
    CREATED_AT         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PIN_LIKE
(
    NO            BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '좋아요 고유번호',
    TARGET_PIN_NO BIGINT NOT NULL COMMENT '좋아요 타겟 게시물',
    LIKER         BIGINT NOT NULL COMMENT '좋아요 누른 사용자 번호',
    EMOJI_NO      INT    NOT NULL COMMENT '0: 좋은 아이디어에요, 1: 좋아요, 2: 감사합니다, 3: 우와, 4: 재미있어요',
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

