CREATE TABLE IF NOT EXISTS PIN
(
    NO                 BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '핀 고유번호',
    USER_NO            BIGINT        NOT NULL COMMENT '핀 작성자 고유번호(FK)',
    IMG_URL            VARCHAR(1024) NOT NULL COMMENT '핀 이미지 URL',
    TITLE              VARCHAR(255) COMMENT '핀 제목',
    DESCRIPTION        TEXT COMMENT '핀 설명',
    LINK               VARCHAR(2000) COMMENT '링크 URL',
    BOARD_NO           BIGINT        NOT NULL COMMENT '보드 종류(FK)',
    IS_COMMENT_ALLOWED BOOLEAN       NOT NULL DEFAULT TRUE COMMENT '댓글 달기 허용여부',
    LIKE_COUNT         INT                    DEFAULT 0 COMMENT '좋아요 수',
    IS_PIN_DELETED     BOOLEAN                DEFAULT FALSE COMMENT '핀 삭제 여부',
    CREATED_AT         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         TIMESTAMP              DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PIN_TAG
(
    NO     BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '핀 - 태그 고유번호',
    PIN_NO BIGINT NOT NULL COMMENT '연관 핀 번호',
    TAG_NO BIGINT NOT NULL COMMENT '연관 태그 번호'
);

CREATE TABLE IF NOT EXISTS TAG
(
    NO         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '태그 고유번호',
    CATEGORY_NO BIGINT COMMENT '카테고리 번호',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `CATEGORY` (
                                          `NO` bigint PRIMARY KEY COMMENT '핀 카테고리 고유번호',
                                          `NAME` varchar(255) NOT NULL COMMENT '카테고리 이름',
                                          `PARENT_NO` bigint COMMENT '부모 카테고리'
);

ALTER TABLE PIN_TAG
    ADD FOREIGN KEY (TAG_NO) REFERENCES TAG (NO);
