### 임시 핀 생성
POST {{url}}/api/pins/pin/temp/v1
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="imageFile"; filename="img.jpg"
Content-Type: image/jpeg

< C:\Users\ipeac\IdeaProjects\backend\api\sample-image\img.png
--WebAppBoundary--


### 임시 핀 조회
# @no-redirect
GET {{url}}/api/pins/pin/temp/670e6bab9ccc8f0f83552a10/v1
Content-Type: application/json

### 임시 핀 리스트 조회
# @no-redirect
GET {{url}}/api/pins/pin/temps/qkrtkdwns3410@gmail.com/v1
Content-Type: application/json

### 임시 핀 수정
# @no-redirect
PUT {{url}}/api/pins/pin/temp/670e6bab9ccc8f0f83552a10/v1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description": "임시 핀 수정",
    "title": "임시 핀 수정",
    "isCommentAllowed": true,
    "link": "https://www.airbnb.co.kr/rooms/2"
}

### 핀 생성 테스트
# @no-redirect
POST {{url}}/api/pins/pin/v1
Content-Type: application/json

{
    "boardNo": 1,
    "description": "핀 생성 테스트",
    "title": "핀 생성 테스트",
    "isCommentAllowed": true,
    "link": "https://www.airbnb.co.kr/rooms/2",
    "imgUrl": "https://www.airbnb.co.kr/rooms/1000",
    "imageClassification": "야경",
    "tagNos": [1, 2],
    "userNo": 1
}

### 핀 수정 테스트
# @no-redirect
PUT {{url}}/api/pins/pin/1/v1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boardNo": 1,
    "description": "핀 수정 테스트",
    "title": "핀 수정 테스트",
    "isCommentAllowed": true,
    "link": "https://www.airbnb.co.kr/rooms/2"
}

### 핀 삭제 테스트
# @no-redirect
DELETE {{url}}/api/pins/pin/1/v1
Content-Type: application/json
Authorization: Bearer {{token}}

### 핀 히스토리 강제 저장
# @no-redirect
POST {{url}}/api/pin-history/v1?userNo=1&pinNo=1
Content-Type: application/json

### DB 핀을 메모리에 올리기
POST {{url}}/api/pins/pin/force-update-to-redis-batch/v1

### 핀 메인 조회
GET {{url}}/api/pins/pin/v1?userNo=1&page=0&pageSize=10
Content-Type: application/json
