### 임시 핀 생성
POST {{url}}/api/pins/pin/temp/v1
Content-Type: application/json

{
    "imageUrl": "https://www.airbnb.co.kr/rooms/1000",
    "userNo": 1
}


### 임시 핀 조회
GET {{url}}/api/pins/pin/temp/66db19ab780f854bb2e0f8a8/v1
Content-Type: application/json

### 임시 핀 리스트 조회
GET {{url}}/api/pins/pin/temps/1/v1
Content-Type: application/json

### 임시 핀 업데이트
PUT {{url}}/api/pins/pin/temp/66db19ab780f854bb2e0f8a8/v1
Content-Type: application/json

{
    "boardNo": 1,
    "description": "임시 핀 업데이트",
    "title": "임시 핀 업데이트",
    "isCommentAllowed": true,
    "link": "https://www.airbnb.co.kr/rooms/2"
}

### 핀 생성 테스트
POST {{url}}/api/pins/pin/v1
Content-Type: application/json

{
    "boardNo": 1,
    "description": "핀 생성 테스트",
    "title": "핀 생성 테스트",
    "isCommentAllowed": true,
    "link": "https://www.airbnb.co.kr/rooms/2",
    "imgUrl": "https://www.airbnb.co.kr/rooms/1000",
    "tagNos": [1, 2],
    "userNo": 1
}
